import type { Metadata } from "next";

import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/layout/Header";
import Sidebar from "@/components/layout/Sidebar";
import PlayerBar from "@/components/layout/PlayerBar";

const interFont = localFont({
  src: [
    { path: "../asset/font/Inter-Light.woff2", weight: "300", style: "normal" },
    { path: "../asset/font/Inter-Regular.woff2", weight: "400", style: "normal" },
    { path: "../asset/font/Inter-Medium.woff2", weight: "500", style: "normal" },
    { path: "../asset/font/Inter-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../asset/font/Inter-Bold.woff2", weight: "700", style: "normal" },
    { path: "../asset/font/Inter-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "../asset/font/Inter-Black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-inter",
  display: "swap",
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { PlayerProvider } from "@/context/PlayerContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning className={`${interFont.variable} h-full antialiased`}>
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
      </head>
      <body suppressHydrationWarning className="h-screen flex flex-col overflow-hidden bg-black text-neutral-200">
        <PlayerProvider>
          <div className="flex-1 flex overflow-hidden">
            <Sidebar />
            <div className="flex-1 flex flex-col h-full overflow-y-auto relative bg-[#121212]">
              <Header />
              <main className="flex-1 w-full flex flex-col text-neutral-100">{children}</main>
            </div>
          </div>
          <PlayerBar />
        </PlayerProvider>
      </body>
    </html>
  );
}
